<?php

namespace ContainerXLe0Pxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6uizWfFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6uizWfF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6uizWfF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'plat' => ['privates', '.errored..service_locator.6uizWfF.App\\Entity\\Plat', NULL, 'Cannot autowire service ".service_locator.6uizWfF": it needs an instance of "App\\Entity\\Plat" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'plat' => 'App\\Entity\\Plat',
            'entityManager' => '?',
        ]);
    }
}
