<?php

namespace ContainerXigkccb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIngredientControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uch.bxE.App\Controller\API\IngredientController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Uch.bxE.App\\Controller\\API\\IngredientController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ingredient' => ['privates', '.errored..service_locator.Uch.bxE.App\\Entity\\Ingredient', NULL, 'Cannot autowire service ".service_locator.Uch.bxE": it needs an instance of "App\\Entity\\Ingredient" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ingredient' => 'App\\Entity\\Ingredient',
        ]))->withContext('App\\Controller\\API\\IngredientController::show()', $container);
    }
}
