<?php

namespace ContainerXigkccb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6uizWfF.App\Entity\Plat' shared service.
     *
     * @return \App\Entity\Plat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6uizWfF": it needs an instance of "App\\Entity\\Plat" but this type has been excluded in "config/services.yaml".');
    }
}
