<?php

namespace ContainerXigkccb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6uizWfF.App\Controller\Admin\PlatController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6uizWfF.App\\Controller\\Admin\\PlatController::delete()'] = ($container->privates['.service_locator.6uizWfF'] ?? $container->load('get_ServiceLocator_6uizWfFService'))->withContext('App\\Controller\\Admin\\PlatController::delete()', $container);
    }
}
