<?php

namespace ContainerXigkccb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6uizWfF.App\Controller\Admin\PlatController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.6uizWfF'] ?? $container->load('get_ServiceLocator_6uizWfFService'));

        if (isset($container->privates['.service_locator.6uizWfF.App\\Controller\\Admin\\PlatController::edit()'])) {
            return $container->privates['.service_locator.6uizWfF.App\\Controller\\Admin\\PlatController::edit()'];
        }

        return $container->privates['.service_locator.6uizWfF.App\\Controller\\Admin\\PlatController::edit()'] = $a->withContext('App\\Controller\\Admin\\PlatController::edit()', $container);
    }
}
