<?php

namespace ContainerXigkccb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mfgUXI5.App\Controller\API\PlatController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mfgUXI5.App\\Controller\\API\\PlatController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'plat' => ['privates', '.errored..service_locator.mfgUXI5.App\\Entity\\Plat', NULL, 'Cannot autowire service ".service_locator.mfgUXI5": it needs an instance of "App\\Entity\\Plat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'plat' => 'App\\Entity\\Plat',
        ]))->withContext('App\\Controller\\API\\PlatController::show()', $container);
    }
}
