<?php

namespace ContainerXigkccb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VNcvkjP.App\Controller\API\PlatController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VNcvkjP.App\\Controller\\API\\PlatController::create()'] = ($container->privates['.service_locator.VNcvkjP'] ?? $container->load('get_ServiceLocator_VNcvkjPService'))->withContext('App\\Controller\\API\\PlatController::create()', $container);
    }
}
